# WARNING - Generated by {fusen} from /dev/prsr.Rmd: do not edit by hand

test_that("plink_prs works", {
  # load weights file into dataframe
  weights_df <- fs::path_package("extdata", "PGS000667-PMBB.txt", package = "prsr") %>%
    vroom::vroom()

  # calculate prs
  prs_res <- plink_prs(
    base_df = weights_df,
    id_col = variant,
    effect_allele_col = effect_allele,
    effect_size_col = effect_weight_mg_dl,
    pfile_dir = "/project/PMBB/PMBB-Release-2020-2.0/Imputed/pgen/",
    plink_bin = "/scratch/Applications/PLINK/plink2_linux_x86_64_20211125/plink2a"
  )
  skip_on_cran()
  skip_on_ci()
  expect_s3_class(prs_res, "data.frame")
})
